######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 2 21:59:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              rtcfg_DM365 \
              rtcfg_local_evm3530_linux \
              rtcfg_local_evm3530_wince \
              rtcfg_remote_evm3530_linux \
              rtcfg_remote_evm3530_wince
INCLUDEPATH += .

# Input
HEADERS += smain.h
SOURCES += app.c \
           main_BIOS.c \
           main_native.c \
           rtcfg_DM365/app_config.c \
           rtcfg_DM365/DM365_config.c \
           rtcfg_DM365/rtcfg_dman3.c \
           rtcfg_local_evm3530_linux/app_config.c \
           rtcfg_local_evm3530_linux/evm3530_config.c \
           rtcfg_local_evm3530_linux/rtcfg_dman3.c \
           rtcfg_local_evm3530_wince/app_config.c \
           rtcfg_local_evm3530_wince/evm3530_config.c \
           rtcfg_local_evm3530_wince/rtcfg_dman3.c \
           rtcfg_remote_evm3530_linux/app_config.c \
           rtcfg_remote_evm3530_linux/evm3530_config_all.c \
           rtcfg_remote_evm3530_wince/app_config.c \
           rtcfg_remote_evm3530_wince/evm3530_config_all.c
