#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/ce/examples/apps/video_copy
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/platforms/evm3530/Platform.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/platforms/evm3530/Platform.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/codec-engine_2_26_01_09/examples/ti/sdo/ce/examples/buildutils/Platforms.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/codec-engine_2_26_01_09/examples/ti/sdo/ce/examples/buildutils/Platforms.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/BuildEnvironment.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_code.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_code.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3Sx9xx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3Sx9xx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TNETV107X.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TNETV107X.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C642x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C642x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_128K.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_128K.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xdc.tci:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xdc.tci
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320DA8xx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320DA8xx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Script.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Script.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6428.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6428.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/include/utils.tci:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/include/utils.tci
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IOMAP2x3x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IOMAP2x3x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C6x0x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C6x0x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Library.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Library.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM6467.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM6467.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM730.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM730.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRA44x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRA44x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CF761990.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CF761990.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IDaVinci.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IDaVinci.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320C5912.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320C5912.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Executable.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Executable.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IOMAP3xxx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IOMAP3xxx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/_utils.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/_utils.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IHimalaya.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IHimalaya.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv6.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRx40x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRx40x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS470R10.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS470R10.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6421.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6421.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM648.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM648.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/codec-engine_2_26_01_09/examples/config.bld:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/codec-engine_2_26_01_09/examples/config.bld
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C6x1x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C6x1x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TNETV107X.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TNETV107X.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS570PSF762.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS570PSF762.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320C1030.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320C1030.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM647.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM647.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/ITarget.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/ITarget.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS570LS20216.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS570LS20216.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_256K.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_256K.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM740.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM740.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3Sx7xx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3Sx7xx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/MVArm9.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/MVArm9.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRA45x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDRA45x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/IOMAP2x3x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/IOMAP2x3x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/UCArm9.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/UCArm9.xs
package.mak: package.bld
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/_gen.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/_gen.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/Utils.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/Utils.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/services/global/Clock.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/services/global/Clock.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xmlgen.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xmlgen.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6486.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6486.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM355.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM355.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6484.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6484.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320DM357.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320DM357.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/PackageContents.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/PackageContents.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ITMS320DA8xx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ITMS320DA8xx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM510.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM510.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/arm/WinCE.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/arm/WinCE.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDM6467.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CDM6467.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/Mingw.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/Mingw.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_data.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_data.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CTNETV2685.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CTNETV2685.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/package.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/package.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM6431.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320CDM6431.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3SxBxx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/ILM3SxBxx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/IOMAP3xxx.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/IOMAP3xxx.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM730.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM730.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6497.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6497.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6496.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI6496.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/CortexM3.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/CortexM3.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/ITarget.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/ITarget.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/IPlatform.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/IPlatform.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Repository.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Repository.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/c6x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/c6x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_512K.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_512K.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/ITarget.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/targets/ITarget.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/ITarget.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/ITarget.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IAntara.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/IAntara.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI648x.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320CTCI648x.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320DM365.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320DM365.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Utils.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/Utils.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6454.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6454.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM6446.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM6446.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/template.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/template.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/om2.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/om2.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM740.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/arm/TMS320CDM740.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/Win32.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/microsoft/targets/Win32.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6452.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/TMS320C6452.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/Linux86.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/Linux86.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv7A.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xmlgen2.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/xmlgen2.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/ExeContext.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/platform/ExeContext.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/services/global/Trace.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/services/global/Trace.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_1M.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/ti/catalog/c6000/ITMS320C64_1M.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/bld/ITargetFilter.xs
/home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/IPackage.xs:
package.mak: /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/xdc/IPackage.xs
endif

gnu.targets.arm.GCArmv5T.rootDir ?= /home/jack/new/arm/4.3.2
gnu.targets.arm.packageBase ?= /home/jack/ti-dvsdk_dm3730-evm_4_01_00_09/xdctools_3_16_03_36/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.ov5T
.PHONY: all,v5T .dlls,v5T .executables,v5T test,v5T
all,v5T: .executables,v5T
.executables,v5T: .libraries,v5T
.executables,v5T: .dlls,v5T
.dlls,v5T: .libraries,v5T
.libraries,v5T: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,v5T
	@$(ECHO) xdc .executables,v5T
	@$(ECHO) xdc .libraries,v5T
	@$(ECHO) xdc .dlls,v5T

all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ce.examples.apps.video_copy.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.apps.video_copy" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,v5T .executables: bin/ti_platforms_evm3530/app_local.xv5T

-include package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.dep
endif
package/cfg/bin/ti_platforms_evm3530/app_local/main_native.ov5T package/cfg/bin/ti_platforms_evm3530/app_local/app.ov5T package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.ov5T : | package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.xdl
bin/ti_platforms_evm3530/app_local.xv5T:
	$(RM) $@
	@$(MSG) lnkv5T $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-g++    -o $@ package/cfg/bin/ti_platforms_evm3530/app_local/main_native.ov5T package/cfg/bin/ti_platforms_evm3530/app_local/app.ov5T package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.ov5T  package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.xdl  -lstdc++ -L$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/lib -lopencv_core  -lopencv_imgproc  -lhighgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann -lpthread -lrt
	
bin/ti_platforms_evm3530/app_local.xv5T:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,v5T))
bin/ti_platforms_evm3530/app_local.xv5T package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.c: .libraries,v5T
endif

package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.c package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.h package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.xdl: override _PROG_NAME := bin/ti_platforms_evm3530/app_local.xv5T
package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.c: package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.cfg
bin/ti_platforms_evm3530/app_local.test test,v5T test: bin/ti_platforms_evm3530/app_local.xv5T.test

bin/ti_platforms_evm3530/app_local.xv5T.test:: bin/ti_platforms_evm3530/app_local.xv5T
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 bin/ti_platforms_evm3530/app_local.xv5T.test
else
	@$(MSG) running $<  ...
	$(call EXEC.bin/ti_platforms_evm3530/app_local.xv5T, ) 
endif


clean:: clean,v5T
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.cfg
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.dep
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.c
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.xdc.inc

clean,v5T::
	-$(RM) bin/ti_platforms_evm3530/app_local.xv5T
	-$(RM) bin/ti_platforms_evm3530/.tmp,app_local.xv5T,*

.executables,v5T .executables: bin/ti_platforms_evm3530/app_remote.xv5T

-include package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.dep
endif
package/cfg/bin/ti_platforms_evm3530/app_remote/main_native.ov5T package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.ov5T package/cfg/bin/ti_platforms_evm3530/app_remote/app.ov5T : | package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.xdl
bin/ti_platforms_evm3530/app_remote.xv5T:
	$(RM) $@
	@$(MSG) lnkv5T $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-g++    -o $@ package/cfg/bin/ti_platforms_evm3530/app_remote/main_native.ov5T package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.ov5T package/cfg/bin/ti_platforms_evm3530/app_remote/app.ov5T  package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.xdl  -lstdc++ -L$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/lib -lopencv_core  -lopencv_imgproc  -lhighgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann -lpthread -lrt
	
bin/ti_platforms_evm3530/app_remote.xv5T:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,v5T))
bin/ti_platforms_evm3530/app_remote.xv5T package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.c: .libraries,v5T
endif

package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.c package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.h package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.xdl: override _PROG_NAME := bin/ti_platforms_evm3530/app_remote.xv5T
package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.c: package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.cfg
bin/ti_platforms_evm3530/app_remote.test test,v5T test: bin/ti_platforms_evm3530/app_remote.xv5T.test

bin/ti_platforms_evm3530/app_remote.xv5T.test:: bin/ti_platforms_evm3530/app_remote.xv5T
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 bin/ti_platforms_evm3530/app_remote.xv5T.test
else
	@$(MSG) running $<  ...
	$(call EXEC.bin/ti_platforms_evm3530/app_remote.xv5T, ) 
endif


clean:: clean,v5T
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.cfg
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.dep
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.c
	-$(RM) package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.xdc.inc

clean,v5T::
	-$(RM) bin/ti_platforms_evm3530/app_remote.xv5T
	-$(RM) bin/ti_platforms_evm3530/.tmp,app_remote.xv5T,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: main_native.ov5T,copy
main_native.ov5T,copy : main_native.ov5T,0,copy main_native.ov5T,1,copy 
	@

main_native.ov5T,0,copy : package/cfg/bin/ti_platforms_evm3530/app_local/main_native.ov5T
main_native.ov5T,1,copy : package/cfg/bin/ti_platforms_evm3530/app_remote/main_native.ov5T
app_remote_xv5T.ov5T,copy : package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.ov5T
.PHONY: main_native.sv5T,copy
main_native.sv5T,copy : main_native.sv5T,0,copy main_native.sv5T,1,copy 
	@

main_native.sv5T,0,copy : package/cfg/bin/ti_platforms_evm3530/app_local/main_native.sv5T
main_native.sv5T,1,copy : package/cfg/bin/ti_platforms_evm3530/app_remote/main_native.sv5T
app_remote_xv5T.sv5T,copy : package/cfg/bin/ti_platforms_evm3530/app_remote_xv5T.sv5T
.PHONY: app.ov5T,copy
app.ov5T,copy : app.ov5T,0,copy app.ov5T,1,copy 
	@

app.ov5T,0,copy : package/cfg/bin/ti_platforms_evm3530/app_local/app.ov5T
app.ov5T,1,copy : package/cfg/bin/ti_platforms_evm3530/app_remote/app.ov5T
app_local_xv5T.ov5T,copy : package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.ov5T
.PHONY: app.sv5T,copy
app.sv5T,copy : app.sv5T,0,copy app.sv5T,1,copy 
	@

app.sv5T,0,copy : package/cfg/bin/ti_platforms_evm3530/app_local/app.sv5T
app.sv5T,1,copy : package/cfg/bin/ti_platforms_evm3530/app_remote/app.sv5T
app_local_xv5T.sv5T,copy : package/cfg/bin/ti_platforms_evm3530/app_local_xv5T.sv5T

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_apps_video_copy
ti_sdo_ce_examples_apps_video_copy.tar: package/build.cfg
ti_sdo_ce_examples_apps_video_copy.tar: package/package.ext.xml
ti_sdo_ce_examples_apps_video_copy.tar: package/package.xdc.inc
ti_sdo_ce_examples_apps_video_copy.tar: package/package.bld.xml
ti_sdo_ce_examples_apps_video_copy.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_ce_examples_apps_video_copy.tar.dep
endif
package/rel/ti_sdo_ce_examples_apps_video_copy/ti/sdo/ce/examples/apps/video_copy/package/package.rel.xml:

ti_sdo_ce_examples_apps_video_copy.tar: package/rel/ti_sdo_ce_examples_apps_video_copy.xdc.inc package/rel/ti_sdo_ce_examples_apps_video_copy/ti/sdo/ce/examples/apps/video_copy/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ce_examples_apps_video_copy.xdc.inc,package/rel/ti_sdo_ce_examples_apps_video_copy.tar.dep)


release release,ti_sdo_ce_examples_apps_video_copy: all ti_sdo_ce_examples_apps_video_copy.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_apps_video_copy.tar
	-$(RM) package/rel/ti_sdo_ce_examples_apps_video_copy.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_apps_video_copy.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) bin/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard bin))
    $(shell $(MKDIR) bin)
endif
ifeq (,$(wildcard bin/ti_platforms_evm3530))
    $(shell $(MKDIR) bin/ti_platforms_evm3530)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/cfg/bin))
    $(shell $(MKDIR) package/cfg/bin)
endif
ifeq (,$(wildcard package/cfg/bin/ti_platforms_evm3530))
    $(shell $(MKDIR) package/cfg/bin/ti_platforms_evm3530)
endif
ifeq (,$(wildcard package/cfg/bin/ti_platforms_evm3530/app_remote))
    $(shell $(MKDIR) package/cfg/bin/ti_platforms_evm3530/app_remote)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/cfg/bin/ti_platforms_evm3530/app_local))
    $(shell $(MKDIR) package/cfg/bin/ti_platforms_evm3530/app_local)
endif
endif
clean::
	-$(RMDIR) package


