######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 2 22:47:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += smain.h
SOURCES += app.c \
           app_scale_old.c \
           app_sobel_by_bmp_image.c \
           main_BIOS.c \
           main_native.c
